### ISSUE TITLE
Generate websites with multiple pages

### ISSUE THREAD

**Issue by bmcandy** [Weaverbeaver/Hugo#7]
Generate a website with the following pages linked together:
- About the company
- CEO Bio
- CTO Bio
- CFO Bio

Similar to this example at Verisign:
https://www.verisign.com/en_US/company-information/burt-kaliski/index.xhtml

**Comment by stephent2023** [comment]
Created multiple_pages.py with this functionality

**Comment by stephent2023** [comment]
Combined multiple_pages.py into web_frontend.py.
